### ISSUE TITLE
Numeric variable labels missing

### ISSUE THREAD

**Issue by wangw106** [atorus-research/dataset-json-hackathon#4]
I am able to read a SEND json file bw.json using read_dataset_json 

bw <- read_dataset_json(  ".../send/bw.json")

I can see all the variable labels in the meta dataframe, but all the labels in the bw dataframe are missing if the type is 
Integer. I am wondering if you can help, attach the bw.json file used. Thanks.

> attributes(bw$BWNOMDY)
NULL
> attributes(bw$BWSEQ)
NULL
> attributes(bw$STUDYID)
$label
[1] "Study Identifier"
[bw.zip](https://github.com/atorus-research/dataset-json-hackathon/files/12480365/bw.zip)

**Comment by bms63** [comment]
This is the successor to our little foray https://atorus-research.github.io/datasetjson/
